### ISSUE TITLE
Numeric cells

### ISSUE THREAD

**Issue by stefanop1** [kawal7415/excel#19]
Thanks for your great plugin.
Is it possible to write numbers in cells and have the sheet treat them as numeric?
Every number I write in a cell results in an alphanumeric cell.
Stefano

**Comment by kawal7415** [comment]
We have headed to give the formula functionality so we had made the cell type dynamic.

You wil be able to see the changes in the next version.

**Comment by kawal7415** [comment]
Excel: ^1.0.9 is out https://pub.dev/packages/excel
CellType Functionality is available in order to save numeric cells
Now excel being **`more faster`** than before.

Added Functionalities:
**Cell Type
Copy Sheet
Rename Sheet
Delete Sheet
Link Sheets
Un-Link Sheets
Font Family (182 Font Family Available)
Font Size
Italic
Underline
Bold**

**Comment by bakua** [comment]
Hello, I have went though the code, but I don't see a way how to set a cell type when creating a new excel file. There isn't any setter for cell type, just getters.

**Comment by kawal7415** [comment]
Hey @bakua , the reason for not giving the setter for cell-type is that, What happens if user sets the setter to int but has String type value in that cell, So when processing the excel file, It will be ambiguous and might lead to corrupted excel file.

So in line : https://github.com/kawal7415/excel/blob/0caf98033f5147f09b96f16270b1a15ce20ccf52/lib/src/sheet/sheet.dart#L877
You can see in the link to internal code that **we have taken the load on us** and **give the users less headache to maintain things**.

**Comment by kawal7415** [comment]
If you set the value to an int then it automatically sets the type to CellType.int

**Comment by bakua** [comment]
I see, that's pretty cool. Thanks for explanation :) Might be worth to mention in docs that  cells are auto typed.
