### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by olsorya2** [kawal7415/excel#39]
I tried to install the latest version of excel and got this error:

> Because every version of flutter_test from sdk depends on xml 3.6.1 and excel >=1.0.4 depends on xml ^4.1.0, flutter_test from sdk is incompatible with excel >=1.0.4.
> So, because flutter_excel_test depends on both excel ^1.1.0 and flutter_test any from sdk, version solving failed.
> pub get failed (1; So, because flutter_excel_test depends on both excel ^1.1.0 and flutter_test any from sdk, version solving failed.)

I'm using Flutter V 1.17.5. Any ideas on how to fix this?

**Comment by kuskhan** [comment]
I'm not sure that this is a right way. But, temporarily it works for me.

Add these lines in `pubspec.yaml` file
```yaml
dependency_overrides:
  xml: ^4.1.0
  petitparser: ^3.0.0
```

Then run `$ flutter pub get`.

Reference articles: 
- https://stackoverflow.com/questions/61135352/cant-add-last-xml-version-to-flutter-project
- https://stackoverflow.com/questions/61485627/unable-to-use-hive-plugin-in-flutter

**Comment by kawal7415** [comment]
Similar issues have been solved in the past,

You can see in the documentation section : https://github.com/kawal7415/excel#frequent-issues

**Comment by kawal7415** [comment]
I hope that the issue is resolve by the above stated solutions.

If there any other issue occurs, feel free to open or re-open the issue again

~~ Happy to help.

**Comment by azmasamy** [comment]
I'm getting this error:
`Because excel >=1.0.4 <2.0.0-null-safety depends on xml ^4.1.0 and apk_analysis depends on xml ^5.0.2, excel >=1.0.4 <2.0.0-null-safety is forbidden.
So, because apk_analysis depends on excel ^1.1.5, version solving failed.
pub get failed (1; So, because apk_analysis depends on excel ^1.1.5, version solving failed.)`

**Comment by azmasamy** [comment]
I tried the solution here: #25 
It just gave me another error:
`Because excel <2.0.0-null-safety depends on archive ^2.0.0 and apk_analysis depends on archive ^3.1.2, excel <2.0.0-null-safety is forbidden.
So, because apk_analysis depends on excel ^1.1.5, version solving failed.
pub get failed (1; So, because apk_analysis depends on excel ^1.1.5, version solving failed.)`
